### PR TITLE
Making package BigQuery compatible

### PR DESCRIPTION
**Pull request by DylanBaker**
A handful of changes in here to make the package BigQuery compatible:

* Adds a `nested_field` macro which formats columns correctly, depending on the warehouse it is using. (This change has only been pushed for the Stitch data, which was the source it was being tested on.)
* Add a `stitch_base-table` macro, which de-dupes Stitch data on BigQuery
* Changes `concat` to `dbt_utils.concat` macro for cross-db support.

I think the two new macros could _probably_ move to https://github.com/fishtown-analytics/stitch-utils. We implemented specifically for this repo. Thought it might be easier to first push this change and then discuss the broader implications for the stitch-utils package after. Happy to discuss!

### CODE REVIEW

**Comment by DylanBaker** [comment]
@axelazaid @jtcohen6 Thought you two might be the best two to discuss with?

**Comment by jtcohen6** [comment]
@DylanBaker I'd be very open to bringing `nested_data` and `stitch_base_table` into stitch-utils! (I've previously thought about adding something along the lines of the latter, so very happy to see it here.) Happy to work on this before, after, or alongside the current PR :)

**Comment by DylanBaker** [comment]
@jtcohen6 I think my preference would be to do it in the following order (in part because I think it's easiest and in part because I'm most interested in getting it into facebook-ads quickest):

* work on this here and merge into facebook-ads
* bring the necessary logic into the stitch-utils package
* change the facebook-ads package to use the logic from stitch-utils

Does that sound good to you?

**Comment by Qashraf** [comment]
Hey @jtcohen6 , Not sure what the update with this is but like I mentioned @DylanBaker I used this branch and it worked for my needs.  It seems like there's a conflict but that could probably be cleaned up with potentially an additional bigquery variable? Let me know if there's anything I can do to help get this PR cleaned up and added to to the package  for everyone to use

**Comment by clrcrl** [comment]
Closing since it's stale

**Pull request closed without merging**
